package com.gentics.kitchenoffice.webapp.view.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class CommentLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout commentHolder;
	@AutoGenerated
	private TextArea commentInput;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CommentLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// commentInput
		commentInput = new TextArea();
		commentInput.setImmediate(false);
		commentInput.setWidth("100.0%");
		commentInput.setHeight("80px");
		commentInput.setInputPrompt("write a comment");
		mainLayout.addComponent(commentInput);
		
		// commentHolder
		commentHolder = new VerticalLayout();
		commentHolder.setImmediate(false);
		commentHolder.setWidth("100.0%");
		commentHolder.setHeight("100.0%");
		commentHolder.setMargin(false);
		mainLayout.addComponent(commentHolder);
		mainLayout.setExpandRatio(commentHolder, 1.0f);
		
		return mainLayout;
	}

}
