package com.gentics.kitchenoffice.webapp.view.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

public class HomeLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pastLayout;
	@AutoGenerated
	private HorizontalLayout proposalLayout;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HomeLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// proposalLayout
		proposalLayout = new HorizontalLayout();
		proposalLayout.setCaption("Today meal proposals");
		proposalLayout.setImmediate(false);
		proposalLayout.setWidth("100.0%");
		proposalLayout.setHeight("250px");
		proposalLayout.setMargin(true);
		proposalLayout.setSpacing(true);
		mainLayout.addComponent(proposalLayout);
		
		// pastLayout
		pastLayout = new VerticalLayout();
		pastLayout.setCaption("past meals");
		pastLayout.setImmediate(false);
		pastLayout.setWidth("100.0%");
		pastLayout.setHeight("100.0%");
		pastLayout.setMargin(false);
		mainLayout.addComponent(pastLayout);
		mainLayout.setExpandRatio(pastLayout, 1.0f);
		
		return mainLayout;
	}

	public VerticalLayout getMainLayout() {
		return mainLayout;
	}

	public VerticalLayout getPastLayout() {
		return pastLayout;
	}

	public HorizontalLayout getProposalLayout() {
		return proposalLayout;
	}
	
	
	

}
