package com.gentics.kitchenoffice.webapp.view;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.VerticalLayout;


@Component
@Scope("session")
public class StandardErrorView extends VerticalLayout implements View{

	@AutoGenerated
	private Link link_1;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public StandardErrorView() {
		buildMainLayout();

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// common part: create layout
		
		setImmediate(false);
		setWidth("100%");
		setHeight("100%");
		setMargin(false);
		setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Sorry, the specified page is not reachable");
		addComponent(label_1);
		setComponentAlignment(label_1, new Alignment(24));
		
		// link_1
		link_1 = new Link("go to home", new ExternalResource("#!" + HomeView.NAME));
		link_1.setImmediate(false);
		link_1.setWidth("-1px");
		link_1.setHeight("-1px");
		addComponent(link_1);
		setComponentAlignment(link_1, new Alignment(20));
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		
	}

}
